GET http://localhost:3000/users/

###

POST http://localhost:3000/users/add
Content-Type: application/json

{
    "name": "Bailey",
    "password": "Test",
    "email": "bailey@mail.com"
}

###

POST http://localhost:3000/users/login
Content-Type: application/json

{
    "email": "bailey@mail.com",
    "password": "Test"
}

###

GET http://localhost:3000/results/c2d871dc-9b1c-451d-8176-67adb83b9d7f

###
